Add jxr variants to quality measure
AIS-22/UNI-AIS-MediaDataFormats pull request #79
Opened 2023-11-21 13:15 UTC by HafnerMichael

2023-11-21 14:53 UTC, Xetiic approved these changes
looks good to me

2023-11-21 19:41 UTC, m-langer commented
if possible please add this to the quality.py script before importing cv2

```python
### DISCLAIMER ###
# To imort pillow_heif before cv2 is necessary to avoid a bug in the library
# affected devices: macOS on Apple Silicon
import pillow_heif
pillow_heif.register_heif_opener()
### END DISCLAIMER ###
```

2023-11-21 19:58 UTC, m-langer requested changes

2023-11-21 19:58 UTC, m-langer commented on scripts/quality.py
> +
See: https://github.com/AIS-22/UNI-AIS-MediaDataFormats/pull/79#issuecomment-1821570416

2023-11-22 07:34 UTC, m-langer approved these changes
looks good now

2023-11-22 07:43 UTC, merged